version: "3.7"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      target: base
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /home/node/app/node_modules
      - ./gateway/src:/home/node/app/src
    networks:
      - microservices
    depends_on:
      - template
    environment: 
      - ENDPOINT_TEMPLATE=template
      
  template:
    build:
      context: ./microservices/template
      dockerfile: Dockerfile
      target: base
    volumes:
      - /home/node/app/node_modules
      - ./microservices/template:/home/node/app
    container_name: template-docker
    expose:
      - "8080"
    command: npm run dev
    networks:
      - microservices

networks:
  microservices:
