version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    container_name: template-docker-single
    expose:
      - "8080"
    ports:
      - "4000:8080"
    command: npm run dev
